=== onPHP/onphp-framework/meta/dtd/meta.dtd
<!-- $Id$ -->

<!ELEMENT metaconfiguration (include*, classes*, sources*)>

<!ELEMENT classes (class*)>

<!ELEMENT class (implement*, properties*, pattern)>
<!ATTLIST class
		name		ID #REQUIRED
		type		(final|abstract) #IMPLIED
		extends		CDATA #IMPLIED
		source		CDATA #IMPLIED
		table		CDATA #IMPLIED
>

<!ELEMENT implement EMPTY>
<!ATTLIST implement
		interface	CDATA #REQUIRED
>

<!ELEMENT properties (identifier?, property*)>

<!ELEMENT identifier EMPTY>
<!ATTLIST identifier
		name	CDATA #IMPLIED
		type	CDATA #IMPLIED
		size	CDATA #IMPLIED
		column	CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
		name		CDATA #REQUIRED
		type		CDATA #REQUIRED
		size		CDATA #IMPLIED
		column		CDATA #IMPLIED
		default		CDATA #IMPLIED
		required	(true|false) "false"
		relation	(OneToOne|OneToMany|ManyToMany) #IMPLIED
		fetch		(lazy|cascade) #IMPLIED
>

<!ELEMENT pattern EMPTY>
<!ATTLIST pattern
		name		(
			DictionaryClass
			|AbstractClass
			|StraightMapping
			|EnumerationClass
			|EnumClass
			|SpookedClass
			|SpookedEnumeration
			|SpookedEnum
			|ValueObject
			|InternalClass
		) #REQUIRED
		fetch		(lazy|cascade) #IMPLIED
>

<!ELEMENT sources (source+)>

<!ELEMENT source EMPTY>
<!ATTLIST source
		name	CDATA #REQUIRED
		default	(true|false) "false"
>

<!-- file path is relative to current meta's directory -->
<!ELEMENT include EMPTY>
<!ATTLIST include
		file		CDATA #REQUIRED
		generate	(true|false) "true"
>

=== onPHP/onphp-framework/meta/internal.xml
<?xml version="1.0"?>
<!DOCTYPE metaconfiguration SYSTEM "meta.dtd">

<!-- $Id$ -->

<metaconfiguration><classes>
	<class name="Range">
		<properties>
			<property name="min" type="Integer" required="false" />
			<property name="max" type="Integer" required="false" />
		</properties>
		
		<pattern name="InternalClass" />
	</class>
	
	<class name="DateRange">
		<properties>
			<property name="start" type="Date" required="false" />
			<property name="end" type="Date" required="false" />
		</properties>
		
		<pattern name="InternalClass" />
	</class>
	
	<class name="TimestampRange">
		<properties>
			<property name="start" type="Timestamp" required="false" />
			<property name="end" type="Timestamp" required="false" />
		</properties>
		
		<pattern name="InternalClass" />
	</class>
	
	<class name="IdentifiableObject">
		<implement interface="Identifiable" />
		
		<properties>
			<identifier type="Integer" />
		</properties>
		
		<pattern name="InternalClass" />
	</class>
	
	<class name="IdentifiableTree" extends="IdentifiableObject">
		<implement interface="Stringable" />
		
		<properties>
			<property
				name="parent"
				type="IdentifiableTree"
				relation="OneToOne"
				required="false"
			/>
		</properties>
		
		<pattern name="InternalClass" />
	</class>
	
	<class name="NamedObject" extends="IdentifiableObject">
		<implement interface="Named" />
		<implement interface="Stringable" />
		
		<properties>
			<property name="name" type="String" required="false" />
		</properties>
		
		<pattern name="InternalClass" />
	</class>
	
	<class name="NamedTree" extends="NamedObject">
		<properties>
			<property
				name="parent"
				type="NamedTree"
				relation="OneToOne"
				required="false"
			/>
		</properties>
		
		<pattern name="InternalClass" />
	</class>
</classes></metaconfiguration>

=== onPHP/onphp-framework/test/meta/config.meta.xml
<?xml version="1.0"?>
<!DOCTYPE metaconfiguration SYSTEM "meta.dtd">

<!-- $Id$ -->

<metaconfiguration><classes>

	<class name="Credentials" type="final">
		<properties>
			<property name="nickname" type="String" size="255" required="true" />
			<property name="password" type="FixedLengthString" size="40" required="true" />
		</properties>
		
		<pattern name="ValueObject" />
	</class>

	<class name="Spook">
		<properties>
			<identifier type="Integer" />
		</properties>
		
		<pattern name="SpookedClass" />
	</class>
	
	<class name="TestTree" extends="NamedTree">
		<properties />
		<pattern name="StraightMapping" />
	</class>
	
	<class name="TestRange" extends="DateRange">
		<properties>
			<identifier />
			
			<property name="start" type="Date" required="true" />
			
			<property name="description" type="String" required="false" />
		</properties>
		
		<pattern name="StraightMapping" />
	</class>

	<class name="TestCity" type="final" table="custom_table">
		<properties>
			<identifier />
			
			<property name="name" type="String" size="50" required="true" />
			<property name="capital" type="Boolean" required="true" default="false" />
			<property name="large" type="Boolean" required="false" />
		</properties>
		
		<pattern name="DictionaryClass" fetch="cascade" />
	</class>
	
	<class name="TestEncapsulant">
		<properties>
			<identifier />
			<property name="name" type="String" size="50" required="true" />
			<property name="cities" type="TestCity" relation="ManyToMany" required="false" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>

	<class name="TestUser" type="final">
		<properties>
			<identifier />
			
			<property name="credentials" type="Credentials" required="true" relation="OneToOne" />
			
			<property name="lastLogin" type="Timestamp" required="true" column="very_custom_field_name" />
			<property name="registered" type="Timestamp" required="true" />
			<property name="strangeTime" type="Time" required="false" />
			
			<property name="city" type="TestCity" relation="OneToOne" required="true" />
			
			<property name="firstOptional" type="TestCity" relation="OneToOne" required="false" />
			<property name="secondOptional" type="TestCity" relation="OneToOne" required="false" />
			<property name="parts" type="TestPart" relation="OneToMany" />
			<property name="encapsulants" type="TestEncapsulant" relation="ManyToMany" />
			
			<property name="url" type="HttpUrl" size="256" required="false" />
			<property name="properties" type="Hstore" required="false" />
			
			<property name="ip" type="IpAddress" required="false" />
			
		</properties>
		
		<pattern name="StraightMapping" />
	</class>
	
	<class name="TestPart">
		<properties>
			<identifier />
			<property name="testUser" type="TestUser" relation="OneToOne" required="false" />
			<property name="name" type="String" size="50" required="true" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>
	
	<class name="TestBinaryStuff">
		<properties>
			<identifier type="String" size="40" />
			<property name="data" type="Binary" required="true" />
		</properties>
		<pattern name="StraightMapping" />
	</class>
	
	<class name="TestItem" type="final">
		<properties>
			<identifier />
			<property name="subItems" type="TestSubItem" relation="OneToMany" required="false" />
			<property name="name" type="String" size="50" required="true" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>
	
	<class name="TestSubItem" type="final">
		<properties>
			<identifier />
			<property name="item" type="TestItem" relation="OneToOne" required="true" column="test_item_id" />
			<property name="encapsulant" type="TestEncapsulant" relation="OneToOne" required="true" />
			<property name="name" type="String" size="50" required="true" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>
	
	<class name="TestParentObject" type="final">
		<properties>
			<identifier />
			<property name="root" column="root_id" type="TestChildObject" relation="OneToOne" fetch="lazy" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>
	
	<class name="TestChildObject" type="final">
		<properties>
			<identifier />
			<property name="parent" column="parent_id" type="TestParentObject" relation="OneToOne" fetch="lazy" required="true" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>

	<class name="TestSelfRecursion" type="final">
		<properties>
			<identifier />
			<property name="parent" column="parent_id" type="TestSelfRecursion" relation="OneToOne" fetch="lazy" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>
	
	<class name="ImageType" type="final">
		<properties>
			<identifier />
		</properties>
		<pattern name="SpookedEnumeration" />
	</class>

	<class name="MimeType" type="final">
		<properties>
			<identifier />
		</properties>
		<pattern name="SpookedEnum" />
	</class>
	
	<class name="TestLazy" type="final">
		<properties>
			<identifier />
			<property name="city" type="TestCity" relation="OneToOne" required="true" fetch="lazy" />
			<property name="cityOptional" type="TestCity" relation="OneToOne" required="false" fetch="lazy" />
			<property name="enum" type="ImageType" relation="OneToOne" required="false" fetch="lazy" />
			<property name="staticEnum" type="MimeType" relation="OneToOne" required="false" fetch="lazy" />
		</properties>
		<pattern name="StraightMapping" />
	</class>
	
	<class name="TestObject" type="final">
		<properties>
				<identifier />
				<property name="types" type="TestType" relation="ManyToMany" required="false" />
				<property name="name" type="String" size="50" required="true" />
		</properties>
		<pattern name="StraightMapping" />
	</class>
	
	<class name="TestType" type="final">
		<properties>
				<identifier />
				<property name="objects" type="TestObject" relation="ManyToMany" required="false" />
				<property name="name" type="String" size="50" required="true" />
		</properties>
		<pattern name="StraightMapping" />
	</class>

	<class name="TestStringIdentifier" type="final">
		<properties>
				<identifier name="id" type="String" size="40" />
				<property name="name" type="String" size="32" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>

	<class name="TestStringIdentifierRelated" type="final">
		<properties>
				<identifier />
				<property name="test" type="TestStringIdentifier" relation="OneToOne" required="false" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>

	<class name="TestContactValue">
		<properties>
			<property name="email" type="String" size="255" required="true" />
			<property name="icq" type="Integer" />
			<property name="phone" type="String" size="255" required="true" />
			<property name="city" type="TestCity" relation="OneToOne" required="true" fetch='lazy' />
		</properties>

		<pattern name="ValueObject" />
	</class>

	<class name="TestUserWithContact" type="final">
		<properties>
			<identifier />
			<property name="name" type="String" size="255" required="true" />
			<property name="surname" type="String" size="255" />			
			<property name="contacts" type="TestContactValue" relation="OneToOne" required="true" />
		</properties>

		<pattern name="StraightMapping" />
	</class>

	<class name="TestContactValueExtended" extends="TestContactValue" type="final">
		<properties>
			<property name="web" type="String" size="255" required="true" />
			<property name="skype" type="String" size="255" required="true" />
		</properties>

		<pattern name="ValueObject" />
	</class>

	<class name="TestUserWithContactExtended" type="final">
		<properties>
			<identifier />
			<property name="name" type="String" size="255" required="true" />
			<property name="surname" type="String" size="255" />
			<property name="contactExt" type="TestContactValueExtended" relation="OneToOne" required="true" />
		</properties>

		<pattern name="StraightMapping" />
	</class>
	
	<class name="TestInternetProvider" type="final">
		<properties>
			<identifier />
			<property name="name" type="String" size="255" required="true" />
			<property name="range" type="IpRange" required="true" />
		</properties>
		<pattern name="DictionaryClass" />
	</class>

</classes></metaconfiguration>

=== onPHP/onphp-framework/doc/project.skel/config.xml
<?xml version="1.0"?>
<!DOCTYPE metaconfiguration SYSTEM "meta.dtd">

<!-- $Id$ -->

<metaconfiguration><classes>

	<class name="Administrator" type="final">
		<properties>
			<identifier name="id" />
			
			<property name="username" type="String" size="64" required="true" />
			<property name="password" type="String" size="40" required="true" />
			
		</properties>
		
		<pattern name="DictionaryClass" />
	</class>

</classes></metaconfiguration>
